apiVersion: v1
entries:
  digispoof-ui:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-27T14:03:02.20989311Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: a4c079aedb1e81dca6806dec26ad9d07847df3f1eebdab1d8d2be6d04c08016d
    home: https://common-ground.dev
    icon: https://common-ground.dev/logo-250x250.png
    name: digispoof-ui
    urls:
    - digispoof-ui-0.1.0.tgz
    version: 0.1.0
  eherkenning-ui:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-07-27T14:03:02.21364471Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 6abf5bf86fe431aee468d50f9f5760f3022ab76a77b8d118946be4c3d1d7a0b6
    home: https://common-ground.dev
    icon: https://common-ground.dev/logo-250x250.png
    name: eherkenning-ui
    urls:
    - eherkenning-ui-0.1.0.tgz
    version: 0.1.0
generated: "2020-07-27T14:03:02.20285771Z"
